// Generated by gencpp from file alma_ros_pkg/AlmaDB.msg
// DO NOT EDIT!


#ifndef ALMA_ROS_PKG_MESSAGE_ALMADB_H
#define ALMA_ROS_PKG_MESSAGE_ALMADB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <alma_ros_pkg/AlmaFmla.h>

namespace alma_ros_pkg
{
template <class ContainerAllocator>
struct AlmaDB_
{
  typedef AlmaDB_<ContainerAllocator> Type;

  AlmaDB_()
    : entries()  {
    }
  AlmaDB_(const ContainerAllocator& _alloc)
    : entries(_alloc)  {
    }



   typedef std::vector< ::alma_ros_pkg::AlmaFmla_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::alma_ros_pkg::AlmaFmla_<ContainerAllocator> >::other >  _entries_type;
  _entries_type entries;




  typedef boost::shared_ptr< ::alma_ros_pkg::AlmaDB_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alma_ros_pkg::AlmaDB_<ContainerAllocator> const> ConstPtr;

}; // struct AlmaDB_

typedef ::alma_ros_pkg::AlmaDB_<std::allocator<void> > AlmaDB;

typedef boost::shared_ptr< ::alma_ros_pkg::AlmaDB > AlmaDBPtr;
typedef boost::shared_ptr< ::alma_ros_pkg::AlmaDB const> AlmaDBConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alma_ros_pkg::AlmaDB_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alma_ros_pkg::AlmaDB_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace alma_ros_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'alma_ros_pkg': ['/home/mcl/ROS/bobdemo_ws/src/alma_ros/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::alma_ros_pkg::AlmaDB_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alma_ros_pkg::AlmaDB_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alma_ros_pkg::AlmaDB_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alma_ros_pkg::AlmaDB_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alma_ros_pkg::AlmaDB_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alma_ros_pkg::AlmaDB_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alma_ros_pkg::AlmaDB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23813a74eebe8f35e8b0ce471b08dff6";
  }

  static const char* value(const ::alma_ros_pkg::AlmaDB_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23813a74eebe8f35ULL;
  static const uint64_t static_value2 = 0xe8b0ce471b08dff6ULL;
};

template<class ContainerAllocator>
struct DataType< ::alma_ros_pkg::AlmaDB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alma_ros_pkg/AlmaDB";
  }

  static const char* value(const ::alma_ros_pkg::AlmaDB_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alma_ros_pkg::AlmaDB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "AlmaFmla[] entries\n\
================================================================================\n\
MSG: alma_ros_pkg/AlmaFmla\n\
# Internal godel-style code for a formula, the formula itself, and whether or not it's currently trusted\n\
int32 code\n\
string fmla\n\
bool trusted\n\
";
  }

  static const char* value(const ::alma_ros_pkg::AlmaDB_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alma_ros_pkg::AlmaDB_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.entries);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AlmaDB_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alma_ros_pkg::AlmaDB_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alma_ros_pkg::AlmaDB_<ContainerAllocator>& v)
  {
    s << indent << "entries[]" << std::endl;
    for (size_t i = 0; i < v.entries.size(); ++i)
    {
      s << indent << "  entries[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::alma_ros_pkg::AlmaFmla_<ContainerAllocator> >::stream(s, indent + "    ", v.entries[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALMA_ROS_PKG_MESSAGE_ALMADB_H
